energy_analytics:
  target: airflow

  outputs:
    airflow:
      type: duckdb
      path: "{{ env_var('ENERGY_ANALYTICS_DB_PATH', '/opt/airflow/project/data/warehouse/energy_analytics.duckdb') }}"
      schema: main
      threads: 1